config/routes.rb
Rails.application.routes.draw do
  resources :notes, path: '/', except: :index
  root to: 'notes#index'

  get '/set_language/:language', to: 'language#set', as: :set_language
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :body, presence: true

  def self.search_by_query(query)
    where("LOWER(title) LIKE ? OR LOWER(body) LIKE ?", "%#{query.downcase}%", "%#{query.downcase}%")
  end

  # private
  
  # def self.escape_sql_pattern(pattern)
  #   pattern.gsub(/[%_\\]/, '\\\\\\&')
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_language

  private

  def set_language
    I18n.locale = params[:language] || cookies[:language] || I18n.default_locale
  end
end

app/controllers/language_controller.rb
class LanguageController < ApplicationController
  def set
    cookies[:language] = params[:language]
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  def index
    @notes = Note.all
    
    case params[:order]
    when 'newest_first'
      @notes = @notes.order(created_at: :desc)
    when 'oldest_first'
      @notes = @notes.order(created_at: :asc)
    when 'alphabetical_asc'
      @notes = @notes.order(:title)
    when 'alphabetical_desc'
      @notes = @notes.order(title: :desc)
    else
      @notes = @notes.order(created_at: :desc)
    end
    
    if params[:query].present?
      @notes = @notes.search_by_query(params[:query])
    end
  
    @grouped_notes = @notes.group_by { |note| note.created_at.strftime('%B %Y') }
  end
  
  

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
  
    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: t('notes.created') }
        format.json { render :show, status: :created, location: @note }
      else
        flash.now[:alert] = @note.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: t('notes.updated') }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: t('notes.deleted') }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_as_localtime(datetime, format = '')
    format = "%d/%b/%Y, %H:%M:%S" unless format.present?
    datetime.localtime.strftime format
  end
end

app/helpers/locale_helper.rb
module LocaleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script type="text/javascript">
  window.translations = {
    dark_mode: "<%= j t('dark_mode') %>",
    light_mode: "<%= j t('light_mode') %>",
  };
</script>
<html>
  <head>
    <title>My note collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to notes_path, class: 'brand-logo center' do %>
          <%= t('title') %>
        <% end %>
        <a href="" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "ES", set_language_path('es'), class: '' %></li>
          <li><%= link_to "EN", set_language_path('en'), class: '' %></li>
          <li><a id="theme-toggle" href="#" class=""><%= t('dark_mode') %></a></li>
        </ul>
      </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
      <li><%= link_to "ES", set_language_path('es'), class: '' %></li>
      <li><%= link_to "EN", set_language_path('en'), class: '' %></li>
      <li><a id="theme-toggle" href="#" class=""><%= t('dark_mode') %></a></li>
    </ul>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <% if I18n.locale == :es %>
        <h5>
          <h5 class="error-title-note center-align"> <%= pluralize(note.errors.count, 'error', 'errores') %> <%= t('errors.notes.count', count: note.errors.count) %></h5>
      <% else %>
        <h5>
          <h5> <%= pluralize(note.errors.count, 'error') %> <%= t('errors.notes.count', count: note.errors.count) %> </h5>
        </h5>
      <% end %>
      <ul>
        <% note.errors.each do |error| %>
          <li>&bull; <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" style="margin-top: 7mm">
    <div class="input-field col s12">
      <%= form.text_field :title, autofocus: true %>
      <%= form.label :title, t('forms.notes.input_title_label') %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_area :body, class: 'materialize-textarea' %>
      <%= form.label :body, t('forms.notes.input_body_label') %>
    </div>
  </div>

  <div class="row">
    <div class="col s12 right-align">
      <button class="btn-flat waves-effect waves-light" type="submit">
        <%= material_icon.send %>
      </button>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="row not-margin-bottom">
    <div class="col s12">
        <div class="row valign-wrapper not-margin-bottom">
          <div class="col s4 m2 center-align">
            <span class="order-text"> <%= t('notes.sorting.label') %></span>
          </div>
          <div class="col s4 m8">
            <%= form_with url: notes_path, method: :get, html: { class: 'input-field select-dropdown game', id: 'orderForm' } do |f| %> 
            <%= f.select :order, options_for_select([
              [t('notes.sorting.newest_first'), 'newest_first'],
              [t('notes.sorting.oldest_first'), 'oldest_first'],
              [t('notes.sorting.alphabetical_asc'), 'alphabetical_asc'],
              [t('notes.sorting.alphabetical_desc'), 'alphabetical_desc']
            ], selected: params[:order]), { class: 'browser-default', name: "order" } %>
            
          </div>
          <div class="col s4 m2">
            <%= f.submit t('notes.sorting.submit'), class: 'btn red', style: "width: 100%" %>
          </div>
        </div>
      
      <% end %>
    </div>
  </div>

   <%= form_with url: notes_path, html: { class: 'input-field col s12' }, method: 'get' do |f| %>
    <%= material_icon.search.css_class('prefix') %>
    <%= f.text_field :query, autofocus: true, placeholder: t('search_placeholder'), value: params.dig(:filters, :query), class: "validate" %>
  <% end %>


  <% @grouped_notes.each do |month, notes| %>
    <div class="month-section">
      <!-- Encabezado del mes -->
      <div class="col s12 section">
        <h4 class="center-align">- <%= month %> -</h4>
      </div>
      
      <% notes.each do |note| %>
        <%= link_to note_path(note) do %>
          <div class="col s12 m6 l4">
            <div class="card">
              <div class="card-content black-text">
                <span class="card-title">
                  <%= note.title %>
                  <span class="right" style="font-size: 50%">
                    <%= format_as_localtime note.created_at %>
                  </span>
                </span>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="fixed-action-btn">
  <%= link_to new_note_path, title: t('new_note'), class: 'btn-floating btn-large pulse tooltipped', data: { tooltip: t('new_note'), position: "left" } do %>
    <%= material_icon.add %>
  <% end %>
</div>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <%= @note.title %>
          <span class="right" style="font-size: 50%">
            <%= format_as_localtime @note.created_at %>
          </span>
        </span>
        <p style="white-space: pre-line"><%= @note.body %></p>
      </div>
      <div class="card-action">
        <%= link_to @note, title: 'Delete', method: :delete, data: { confirm: t('notes.comfirm') }, class: 'black-text' do %>
          <%= material_icon.delete %>
        <% end %>

        <%= link_to edit_note_path(@note), title: 'Edit', class: 'black-text right' do %>
          <%= material_icon.mode_edit %>
        <% end %>
      </div>
    </div>
  </div>
</div>